# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Build and push Docker images
description: Build and push Docker images with Buildx
author: tuxpower
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  DOCKERHUB_USERNAME:
    description: 'Docker Hub username'
    required: true
  DOCKERHUB_TOKEN:
    description: 'Docker Hub token'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.DOCKERHUB_USERNAME }}
      password: ${{ inputs.DOCKERHUB_TOKEN }}

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      push: true
      tags: jgaspar/workflow:latest
